# Generated by Django 2.0 on 2020-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='todo item')),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
