# Generated by Django 3.0.4 on 2020-05-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_updated',
        ),
    ]
