# Generated by Django 3.0.4 on 2020-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
