# Generated by Django 3.0.4 on 2020-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200926_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
